--[[--------------------------------------------------
008_TalentGuides.lua
Authors: theKennethy
Version: 1.05.0
------------------------------------------------------
Description: Talent Build Guides for Vanilla WoW
    - Leveling builds
    - Endgame PvE builds
    - PvP builds
    - Talent order recommendations
------------------------------------------------------
]]--

Table_008_TalentGuides = {
-----------Warrior Talents
	[11001] = {
		title = "Warrior - Leveling Talents",
		items = {
			[1] = { str = "#NPCWarrior Leveling Build# - Arms/Fury Hybrid" },
			[2] = { str = "#DOQUESTRecommended Spec#: Arms to 31, then Fury" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Deflection 5/5 (Arms) - Parry chance" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Tactical Mastery 5/5 (Arms) - Keep rage on stance swap" },
			[5] = { str = "#DOQUESTLevel 20 (1 point)#: Anger Management 1/1 (Arms) - Passive rage gen" },
			[6] = { str = "#DOQUESTLevel 21-22 (2 points)#: Deep Wounds 2/3 (Arms)" },
			[7] = { str = "#DOQUESTLevel 23-24 (2 points)#: Impale 2/2 (Arms) - Crit damage" },
			[8] = { str = "#DOQUESTLevel 25-29 (5 points)#: Two-Handed Weapon Spec 5/5 (Arms)" },
			[9] = { str = "#DOQUESTLevel 30 (1 point)#: Sweeping Strikes 1/1 (Arms) - AoE farming god" },
			[10] = { str = "#DOQUESTLevel 31 (1 point)#: Mortal Strike 1/1 (Arms) - Your main ability!" },
			[11] = { str = "#DOQUESTLevel 32-36 (5 points)#: Cruelty 5/5 (Fury) - 5% crit" },
			[12] = { str = "#DOQUESTLevel 37-41 (5 points)#: Unbridled Wrath 5/5 (Fury) - Rage on hit" },
			[13] = { str = "#DOQUESTLevel 42-46 (5 points)#: Enrage 5/5 (Fury) - Damage after crit" },
			[14] = { str = "#DOQUESTLevel 47-51 (5 points)#: Flurry 5/5 (Fury) - Attack speed after crit" },
			[15] = { str = "#DOQUESTLevel 52-56 (5 points)#: Improved Berserker Rage 2/2 + Improved Execute 2/2 + 1 Deep Wounds" },
			[16] = { str = "#DOQUESTLevel 57-60 (4 points)#: Finish Deep Wounds + Improved Slam or other" },
			[17] = { str = "#TURNINKey Abilities#: Charge > Rend > MS > Overpower procs. Use Sweeping Strikes + Whirlwind for 2+ mobs." },
			[18] = { str = "#DOQUESTTips#: Always use a 2H weapon while leveling. Hamstring kiting works great. Keep Sunder Armor up on tough mobs." },
		}
	},

	[11002] = {
		title = "Warrior - Fury DPS (Raid)",
		items = {
			[1] = { str = "#NPCFury Warrior Raid Build# - Dual Wield DPS" },
			[2] = { str = "#DOQUESTSpec#: 17/34/0 or 20/31/0" },
			[3] = { str = "#DOQUESTArms (17-20 points)#:" },
			[4] = { str = "#ACCEPT- Deflection 5/5# - Parry for survival" },
			[5] = { str = "#ACCEPT- Tactical Mastery 5/5# - Stance dance" },
			[6] = { str = "#ACCEPT- Anger Management 1/1# - Rage gen" },
			[7] = { str = "#ACCEPT- Deep Wounds 3/3# - Bleed damage" },
			[8] = { str = "#ACCEPT- Impale 2/2# - +20% crit damage" },
			[9] = { str = "#ACCEPT- (Optional) Two-Handed Weapon Spec 1/5# - If using Slam build" },
			[10] = { str = "#DOQUESTFury (31-34 points)#:" },
			[11] = { str = "#ACCEPT- Cruelty 5/5# - 5% crit" },
			[12] = { str = "#ACCEPT- Unbridled Wrath 5/5# - Rage on hit" },
			[13] = { str = "#ACCEPT- Improved Battle Shout 5/5# - Group AP buff" },
			[14] = { str = "#ACCEPT- Dual Wield Specialization 5/5# - OH damage" },
			[15] = { str = "#ACCEPT- Enrage 5/5# - Damage buff" },
			[16] = { str = "#ACCEPT- Flurry 5/5# - Attack speed" },
			[17] = { str = "#ACCEPT- Bloodthirst 1/1# - Main ability" },
			[18] = { str = "#ACCEPT- (Optional) Death Wish 1/1# - DPS cooldown" },
			[19] = { str = "#TURNINRotation#: BT > Whirlwind > Heroic Strike (when rage capped). Keep Battle Shout up." },
			[20] = { str = "#DOQUESTStat Priority#: Hit (6% cap) > Crit > AP > Strength" },
		}
	},

	[11003] = {
		title = "Warrior - Protection Tank (Raid)",
		items = {
			[1] = { str = "#NPCProtection Warrior Raid Tank#" },
			[2] = { str = "#DOQUESTSpec#: 11/5/35 (Deep Prot) or 0/5/46 (Full Prot)" },
			[3] = { str = "#DOQUESTArms (0-11 points)#:" },
			[4] = { str = "#ACCEPT- Deflection 5/5# - Parry" },
			[5] = { str = "#ACCEPT- Tactical Mastery 5/5# - Stance swap rage" },
			[6] = { str = "#ACCEPT- Anger Management 1/1# - Rage gen" },
			[7] = { str = "#DOQUESTFury (5 points)#:" },
			[8] = { str = "#ACCEPT- Cruelty 5/5# - Threat from crits" },
			[9] = { str = "#DOQUESTProtection (35-46 points)#:" },
			[10] = { str = "#ACCEPT- Shield Specialization 5/5# - Rage from blocks" },
			[11] = { str = "#ACCEPT- Anticipation 5/5# - Defense skill" },
			[12] = { str = "#ACCEPT- Improved Revenge 3/3# - Stun proc" },
			[13] = { str = "#ACCEPT- Toughness 5/5# - Armor" },
			[14] = { str = "#ACCEPT- Last Stand 1/1# - Emergency HP" },
			[15] = { str = "#ACCEPT- Improved Shield Block 3/3# - Key talent!" },
			[16] = { str = "#ACCEPT- Defiance 5/5# - +15% threat" },
			[17] = { str = "#ACCEPT- Concussion Blow 1/1# - Stun" },
			[18] = { str = "#ACCEPT- One-Handed Weapon Spec 5/5# - Threat" },
			[19] = { str = "#ACCEPT- Shield Slam 1/1# - Main threat ability" },
			[20] = { str = "#TURNINThreat Rotation#: Shield Slam > Revenge > Sunder > Heroic Strike (rage dump). Keep Demo Shout up." },
			[21] = { str = "#DOQUESTStat Priority#: Defense (440 cap) > Stamina > Armor > Hit > Block" },
		}
	},

-----------Rogue Talents
	[11004] = {
		title = "Rogue - Leveling Talents",
		items = {
			[1] = { str = "#NPCRogue Leveling Build# - Combat Swords" },
			[2] = { str = "#DOQUESTRecommended Spec#: Combat all the way!" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Improved Sinister Strike 2/2 + Lightning Reflexes 3/5" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Finish Lightning Reflexes 5/5 + Improved Backstab 2/3" },
			[5] = { str = "#DOQUESTLevel 20-24 (5 points)#: Precision 5/5 - Hit is king!" },
			[6] = { str = "#DOQUESTLevel 25-29 (5 points)#: Dual Wield Specialization 5/5" },
			[7] = { str = "#DOQUESTLevel 30 (1 point)#: Blade Flurry 1/1 - AoE god mode!" },
			[8] = { str = "#DOQUESTLevel 31-35 (5 points)#: Sword Specialization 5/5 - Extra attacks!" },
			[9] = { str = "#DOQUESTLevel 36-39 (4 points)#: Aggression 3/3 + Weapon Expertise 1/2" },
			[10] = { str = "#DOQUESTLevel 40 (1 point)#: Adrenaline Rush 1/1 - Huge cooldown!" },
			[11] = { str = "#DOQUESTLevel 41-45 (5 points)#: Malice 5/5 (Assassination) - 5% crit" },
			[12] = { str = "#DOQUESTLevel 46-50 (5 points)#: Murder 2/2 + Ruthlessness 3/3" },
			[13] = { str = "#DOQUESTLevel 51-55 (5 points)#: Improved Slice and Dice 3/3 + Relentless Strikes 1/1 + 1 point flex" },
			[14] = { str = "#DOQUESTLevel 56-60 (5 points)#: Lethality 5/5 - Crit damage" },
			[15] = { str = "#TURNINRotation#: SS to 5 CP > SnD (first) > Eviscerate. Blade Flurry for 2+ mobs. Use Evasion liberally." },
			[16] = { str = "#DOQUESTTips#: Use the best swords you can find. Thistle Tea for energy. Keep SnD up always!" },
		}
	},

	[11005] = {
		title = "Rogue - Combat Daggers (Raid)",
		items = {
			[1] = { str = "#NPCCombat Daggers Raid Build#" },
			[2] = { str = "#DOQUESTSpec#: 15/31/5" },
			[3] = { str = "#DOQUESTAssassination (15 points)#:" },
			[4] = { str = "#ACCEPT- Improved Eviscerate 3/3#" },
			[5] = { str = "#ACCEPT- Malice 5/5# - 5% crit" },
			[6] = { str = "#ACCEPT- Ruthlessness 3/3#" },
			[7] = { str = "#ACCEPT- Murder 2/2#" },
			[8] = { str = "#ACCEPT- Relentless Strikes 1/1# - Energy refund" },
			[9] = { str = "#ACCEPT- Lethality 1/5# (or Improved SnD)" },
			[10] = { str = "#DOQUESTCombat (31 points)#:" },
			[11] = { str = "#ACCEPT- Improved Backstab 3/3#" },
			[12] = { str = "#ACCEPT- Lightning Reflexes 5/5#" },
			[13] = { str = "#ACCEPT- Precision 5/5# - Hit!" },
			[14] = { str = "#ACCEPT- Dual Wield Specialization 5/5#" },
			[15] = { str = "#ACCEPT- Blade Flurry 1/1#" },
			[16] = { str = "#ACCEPT- Dagger Specialization 5/5#" },
			[17] = { str = "#ACCEPT- Weapon Expertise 2/2#" },
			[18] = { str = "#ACCEPT- Aggression 3/3#" },
			[19] = { str = "#ACCEPT- Adrenaline Rush 1/1#" },
			[20] = { str = "#DOQUESTSubtlety (5 points)#:" },
			[21] = { str = "#ACCEPT- Opportunity 5/5# - Backstab damage" },
			[22] = { str = "#TURNINRotation#: BS to 5 CP > SnD (keep up!) > BS to 5 CP > Eviscerate. Use AR + Blade Flurry together." },
			[23] = { str = "#DOQUESTStat Priority#: Hit (9% yellow cap) > Crit > AP > Agility" },
		}
	},

-----------Mage Talents
	[11006] = {
		title = "Mage - Leveling Talents",
		items = {
			[1] = { str = "#NPCMage Leveling Build# - Frost AoE" },
			[2] = { str = "#DOQUESTRecommended Spec#: Deep Frost for survivability and AoE" },
			[3] = { str = "#DOQUESTLevel 10-12 (3 points)#: Elemental Precision 3/3 (Frost) - Hit!" },
			[4] = { str = "#DOQUESTLevel 13-14 (2 points)#: Improved Frostbolt 2/5" },
			[5] = { str = "#DOQUESTLevel 15-17 (3 points)#: Finish Improved Frostbolt 5/5" },
			[6] = { str = "#DOQUESTLevel 18-19 (2 points)#: Frostbite 2/3 (or Permafrost)" },
			[7] = { str = "#DOQUESTLevel 20 (1 point)#: Cold Snap 1/1 - Reset frost CDs!" },
			[8] = { str = "#DOQUESTLevel 21-22 (2 points)#: Improved Frost Nova 2/2" },
			[9] = { str = "#DOQUESTLevel 23-25 (3 points)#: Piercing Ice 3/3 - +6% frost damage" },
			[10] = { str = "#DOQUESTLevel 26-28 (3 points)#: Shatter 3/3 - Crit frozen targets!" },
			[11] = { str = "#DOQUESTLevel 29 (1 point)#: Ice Block 1/1 - Immunity!" },
			[12] = { str = "#DOQUESTLevel 30 (1 point)#: Ice Barrier 1/1 - Shield!" },
			[13] = { str = "#DOQUESTLevel 31-35 (5 points)#: Arctic Reach 2/2 + Frost Channeling 3/3" },
			[14] = { str = "#DOQUESTLevel 36-39 (4 points)#: Winter's Chill 4/5" },
			[15] = { str = "#DOQUESTLevel 40 (1 point)#: Ice Barrier 1/1 (already have from 30)" },
			[16] = { str = "#DOQUESTLevel 40 AoE Build Option#: Respec to Improved Blizzard 3/3 + Improved Cone of Cold 3/3 for AoE grinding!" },
			[17] = { str = "#TURNINSingle Target#: Frostbolt spam. Frost Nova > Blink if melee. Use Ice Barrier on CD." },
			[18] = { str = "#TURNINAoE Farming#: Gather mobs > Frost Nova > Blizzard > CoC > repeat. Requires practice!" },
			[19] = { str = "#DOQUESTTips#: Conjure water/food. Use Polymorph for tough pulls. Ice Block to reset bad pulls." },
		}
	},

	[11007] = {
		title = "Mage - Fire (Raid DPS)",
		items = {
			[1] = { str = "#NPCFire Mage Raid Build#" },
			[2] = { str = "#DOQUESTSpec#: 17/31/3 (Fire)" },
			[3] = { str = "#DOQUESTNote#: Fire is only viable when boss isn't fire immune (late game)!" },
			[4] = { str = "#DOQUESTArcane (17 points)#:" },
			[5] = { str = "#ACCEPT- Arcane Subtlety 2/2# - Threat reduction" },
			[6] = { str = "#ACCEPT- Arcane Focus 5/5# - Hit for Arcane spells" },
			[7] = { str = "#ACCEPT- Arcane Concentration 5/5# - Clearcasting!" },
			[8] = { str = "#ACCEPT- Arcane Meditation 3/3# - Mana regen" },
			[9] = { str = "#ACCEPT- Arcane Mind 2/5# - Intellect" },
			[10] = { str = "#DOQUESTFire (31 points)#:" },
			[11] = { str = "#ACCEPT- Improved Fireball 5/5# - Faster Fireballs" },
			[12] = { str = "#ACCEPT- Ignite 5/5# - Crit DoT (huge damage!)" },
			[13] = { str = "#ACCEPT- Flame Throwing 2/2# - Range" },
			[14] = { str = "#ACCEPT- Incinerate 2/2# - Crit chance" },
			[15] = { str = "#ACCEPT- Improved Scorch 5/5# - Fire vulnerability debuff" },
			[16] = { str = "#ACCEPT- Master of Elements 3/3# - Mana refund on crit" },
			[17] = { str = "#ACCEPT- Critical Mass 3/3# - Crit chance" },
			[18] = { str = "#ACCEPT- Fire Power 5/5# - +10% fire damage" },
			[19] = { str = "#ACCEPT- Combustion 1/1# - Crit cooldown" },
			[20] = { str = "#TURNINRotation#: Keep Scorch debuff up (5 stacks) > Fireball spam. Use Combustion on pull." },
			[21] = { str = "#DOQUESTStat Priority#: Hit (16% cap) > Spell Crit > Spell Power > Intellect" },
		}
	},

-----------Priest Talents
	[11008] = {
		title = "Priest - Leveling Talents",
		items = {
			[1] = { str = "#NPCPriest Leveling Build# - Shadow (wand spec early)" },
			[2] = { str = "#DOQUESTRecommended Spec#: Discipline start, then Shadow" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Wand Specialization 5/5 (Discipline) - 25% wand damage!" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Spirit Tap 5/5 (Shadow) - Mana regen on kill" },
			[5] = { str = "#DOQUESTLevel 20-22 (3 points)#: Shadow Focus 3/5 (Shadow) - Hit" },
			[6] = { str = "#DOQUESTLevel 23-24 (2 points)#: Improved Shadow Word: Pain 2/2" },
			[7] = { str = "#DOQUESTLevel 25-29 (5 points)#: Mind Flay 1/1 + Shadow Weaving 4/5" },
			[8] = { str = "#DOQUESTLevel 30 (1 point)#: Vampiric Embrace 1/1 - Self healing!" },
			[9] = { str = "#DOQUESTLevel 31-35 (5 points)#: Finish Shadow Weaving 5/5 + Silence 1/1 + Darkness 3/5" },
			[10] = { str = "#DOQUESTLevel 36-39 (4 points)#: Finish Darkness 5/5 + Shadow Reach 2/3" },
			[11] = { str = "#DOQUESTLevel 40 (1 point)#: Shadowform 1/1 - THE talent!" },
			[12] = { str = "#DOQUESTLevel 41-45 (5 points)#: Improved Mind Blast 5/5" },
			[13] = { str = "#DOQUESTLevel 46-50 (5 points)#: Finish Shadow Focus 5/5 + Shadow Reach 3/3" },
			[14] = { str = "#DOQUESTLevel 51-55 (5 points)#: Meditation 3/3 (Disc) + Improved PW:Shield 2/3" },
			[15] = { str = "#DOQUESTLevel 56-60 (5 points)#: Inner Focus 1/1 + Improved PW:Fortitude 2/2 + Mental Agility 2/5" },
			[16] = { str = "#TURNINRotation#: Shield > SW:P > Mind Blast > Mind Flay > Wand to death. Spirit Tap procs = free mana!" },
			[17] = { str = "#DOQUESTTips#: Get the BEST wand you can. Wand DPS is huge early. VE keeps you alive. Never leave Shadowform!" },
		}
	},

	[11009] = {
		title = "Priest - Holy Healer (Raid)",
		items = {
			[1] = { str = "#NPCHoly Priest Raid Healer#" },
			[2] = { str = "#DOQUESTSpec#: 21/30/0 or 26/25/0" },
			[3] = { str = "#DOQUESTDiscipline (21-26 points)#:" },
			[4] = { str = "#ACCEPT- Unbreakable Will 5/5# - Resist silence" },
			[5] = { str = "#ACCEPT- Improved Power Word: Fortitude 2/2#" },
			[6] = { str = "#ACCEPT- Improved Power Word: Shield 3/3#" },
			[7] = { str = "#ACCEPT- Meditation 3/3# - Mana regen in FSR" },
			[8] = { str = "#ACCEPT- Inner Focus 1/1# - Free spell" },
			[9] = { str = "#ACCEPT- Mental Agility 5/5# - Instant cast mana" },
			[10] = { str = "#ACCEPT- (Optional) Divine Spirit 1/1# - Spirit buff" },
			[11] = { str = "#DOQUESTHoly (25-30 points)#:" },
			[12] = { str = "#ACCEPT- Healing Focus 2/2# - No pushback" },
			[13] = { str = "#ACCEPT- Improved Renew 3/3#" },
			[14] = { str = "#ACCEPT- Holy Specialization 5/5# - Crit heals" },
			[15] = { str = "#ACCEPT- Divine Fury 5/5# - Faster heals" },
			[16] = { str = "#ACCEPT- Inspiration 3/3# - Armor buff on crit" },
			[17] = { str = "#ACCEPT- Holy Reach 2/2# - Range" },
			[18] = { str = "#ACCEPT- Improved Healing 3/3# - Mana efficiency" },
			[19] = { str = "#ACCEPT- Spiritual Guidance 5/5# - Spirit to SP" },
			[20] = { str = "#ACCEPT- Spiritual Healing 5/5# - +10% healing" },
			[21] = { str = "#TURNINHealing Priority#: Tank heals with Greater Heal. Raid heals with Flash Heal or Renew. Use Inner Focus for big heals." },
			[22] = { str = "#DOQUESTStat Priority#: +Healing > Spirit > Intellect > MP5" },
		}
	},

-----------Warlock Talents
	[11010] = {
		title = "Warlock - Leveling Talents",
		items = {
			[1] = { str = "#NPCWarlock Leveling Build# - Drain Tank / Affliction" },
			[2] = { str = "#DOQUESTRecommended Spec#: Affliction for efficiency" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Improved Corruption 5/5 - Instant cast!" },
			[4] = { str = "#DOQUESTLevel 15-16 (2 points)#: Suppression 2/5 - Hit" },
			[5] = { str = "#DOQUESTLevel 17-19 (3 points)#: Improved Life Tap 2/2 + Improved Drain Life 1/5" },
			[6] = { str = "#DOQUESTLevel 20 (1 point)#: Fel Concentration 1/5" },
			[7] = { str = "#DOQUESTLevel 21-25 (5 points)#: Finish Fel Concentration 5/5 - No pushback on Drain!" },
			[8] = { str = "#DOQUESTLevel 26-29 (4 points)#: Amplify Curse 1/1 + Grim Reach 2/2 + Nightfall 1/2" },
			[9] = { str = "#DOQUESTLevel 30 (1 point)#: Siphon Life 1/1 - Another DoT!" },
			[10] = { str = "#DOQUESTLevel 31-35 (5 points)#: Shadow Mastery 5/5 - +10% shadow damage" },
			[11] = { str = "#DOQUESTLevel 36-39 (4 points)#: Finish Nightfall 2/2 + Finish Suppression 5/5" },
			[12] = { str = "#DOQUESTLevel 40 (1 point)#: Dark Pact 1/1 - Drain pet mana!" },
			[13] = { str = "#DOQUESTLevel 41-45 (5 points)#: Demonic Embrace 5/5 (Demo) - Stamina" },
			[14] = { str = "#DOQUESTLevel 46-50 (5 points)#: Improved Voidwalker 3/3 + Fel Domination 1/1 + 1 point flex" },
			[15] = { str = "#DOQUESTLevel 51-55 (5 points)#: Improved Drain Life 5/5" },
			[16] = { str = "#DOQUESTLevel 56-60 (5 points)#: Finish Improved Healthstone + Soul Link 1/1 + Fel Stamina" },
			[17] = { str = "#TURNINRotation#: Corruption > CoA > Siphon Life > Drain Life. Never stop, never drink. Use Voidwalker to tank." },
			[18] = { str = "#DOQUESTTips#: Life Tap > Drink. Dark Pact your pet. You can pull endlessly with good DoT management." },
		}
	},

	[11011] = {
		title = "Warlock - SM/Ruin (Raid DPS)",
		items = {
			[1] = { str = "#NPCSM/Ruin Warlock Raid Build#" },
			[2] = { str = "#DOQUESTSpec#: 7/21/23 (Shadow Mastery + Ruin)" },
			[3] = { str = "#DOQUESTAffiction (7 points)#:" },
			[4] = { str = "#ACCEPT- Suppression 3/5# - Hit for Affliction" },
			[5] = { str = "#ACCEPT- Improved Corruption 4/5# (or 5/5)#" },
			[6] = { str = "#DOQUESTDemonology (21 points)#:" },
			[7] = { str = "#ACCEPT- Improved Healthstone 2/2#" },
			[8] = { str = "#ACCEPT- Improved Imp 3/3# - Raid buff (Blood Pact)" },
			[9] = { str = "#ACCEPT- Demonic Embrace 5/5# - Stamina" },
			[10] = { str = "#ACCEPT- Fel Intellect 5/5# - Pet intellect = mana" },
			[11] = { str = "#ACCEPT- Fel Domination 1/1#" },
			[12] = { str = "#ACCEPT- Master Summoner 2/2#" },
			[13] = { str = "#ACCEPT- Demonic Sacrifice 1/1# - Sac Succubus for +15% shadow!" },
			[14] = { str = "#ACCEPT- (Optional) Master Demonologist 1/5#" },
			[15] = { str = "#DOQUESTDestruction (23 points)#:" },
			[16] = { str = "#ACCEPT- Improved Shadow Bolt 5/5# - Debuff on crit" },
			[17] = { str = "#ACCEPT- Cataclysm 5/5# - Mana cost reduction" },
			[18] = { str = "#ACCEPT- Bane 5/5# - Cast time reduction" },
			[19] = { str = "#ACCEPT- Devastation 5/5# - Crit chance" },
			[20] = { str = "#ACCEPT- Shadowburn 1/1# - Execute" },
			[21] = { str = "#ACCEPT- Ruin 1/1# - +100% crit damage!" },
			[22] = { str = "#TURNINRotation#: Sacrifice Succubus > Keep Corruption up > Shadow Bolt spam. Use Shadowburn as execute." },
			[23] = { str = "#DOQUESTStat Priority#: Hit (16% cap) > Spell Crit > Spell Power > Stamina" },
		}
	},

-----------Hunter Talents  
	[11012] = {
		title = "Hunter - Leveling Talents",
		items = {
			[1] = { str = "#NPCHunter Leveling Build# - Beast Mastery" },
			[2] = { str = "#DOQUESTRecommended Spec#: BM for pet tankiness" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Endurance Training 5/5 - Pet HP" },
			[4] = { str = "#DOQUESTLevel 15-16 (2 points)#: Thick Hide 2/3 - Pet armor" },
			[5] = { str = "#DOQUESTLevel 17-19 (3 points)#: Improved Revive Pet 2/2 + Bestial Swiftness 1/1" },
			[6] = { str = "#DOQUESTLevel 20-24 (5 points)#: Unleashed Fury 5/5 - Pet damage!" },
			[7] = { str = "#DOQUESTLevel 25-29 (5 points)#: Ferocity 5/5 - Pet crit" },
			[8] = { str = "#DOQUESTLevel 30 (1 point)#: Intimidation 1/1 - Pet stun!" },
			[9] = { str = "#DOQUESTLevel 31-35 (5 points)#: Frenzy 5/5 - Pet attack speed" },
			[10] = { str = "#DOQUESTLevel 36-39 (4 points)#: Bestial Discipline 2/2 + Spirit Bond 2/2" },
			[11] = { str = "#DOQUESTLevel 40 (1 point)#: Bestial Wrath 1/1 - THE BIG RED PET!" },
			[12] = { str = "#DOQUESTLevel 41-45 (5 points)#: Lethal Shots 5/5 (MM) - Crit" },
			[13] = { str = "#DOQUESTLevel 46-50 (5 points)#: Efficiency 5/5 (MM) - Mana costs" },
			[14] = { str = "#DOQUESTLevel 51-55 (5 points)#: Improved Hunter's Mark 5/5 (MM)" },
			[15] = { str = "#DOQUESTLevel 56-60 (5 points)#: Mortal Shots 5/5 (MM) - Crit damage" },
			[16] = { str = "#TURNINRotation#: Hunter's Mark > Send Pet > Auto Shot > Serpent Sting > Arcane Shot. Multi-Shot for AoE." },
			[17] = { str = "#DOQUESTTips#: Tame a cat or owl for DPS. Keep pet happy! Use Feign Death to reset." },
		}
	},

	[11013] = {
		title = "Hunter - Marksmanship (Raid)",
		items = {
			[1] = { str = "#NPCMarksmanship Hunter Raid Build#" },
			[2] = { str = "#DOQUESTSpec#: 2/31/18 or 0/31/20" },
			[3] = { str = "#DOQUEST(Optional) BM (2 points)#: Improved Aspect of the Hawk 2/5" },
			[4] = { str = "#DOQUESTMarksmanship (31 points)#:" },
			[5] = { str = "#ACCEPT- Efficiency 5/5# - Mana" },
			[6] = { str = "#ACCEPT- Lethal Shots 5/5# - Crit" },
			[7] = { str = "#ACCEPT- Aimed Shot 1/1# - Big hit" },
			[8] = { str = "#ACCEPT- Hawk Eye 3/3# - Range" },
			[9] = { str = "#ACCEPT- Improved Arcane Shot 4/5# (or 5/5)" },
			[10] = { str = "#ACCEPT- Mortal Shots 5/5# - Crit damage" },
			[11] = { str = "#ACCEPT- Barrage 3/3# - Multi-Shot damage" },
			[12] = { str = "#ACCEPT- Ranged Weapon Specialization 5/5# - +5% damage" },
			[13] = { str = "#ACCEPT- Trueshot Aura 1/1# - Raid AP buff!" },
			[14] = { str = "#DOQUESTSurvival (18-20 points)#:" },
			[15] = { str = "#ACCEPT- Monster Slaying 3/3# - +3% damage to beasts" },
			[16] = { str = "#ACCEPT- Humanoid Slaying 3/3# - +3% damage to humanoids" },
			[17] = { str = "#ACCEPT- Clever Traps 2/2#" },
			[18] = { str = "#ACCEPT- Survivalist 5/5# - Stamina" },
			[19] = { str = "#ACCEPT- Surefooted 3/3# - Hit!" },
			[20] = { str = "#ACCEPT- Killer Instinct 2/3# or 3/3" },
			[21] = { str = "#TURNINRotation#: Hunter's Mark > Aimed Shot > Multi-Shot > Auto Shot weaving. Clip auto shots properly!" },
			[22] = { str = "#DOQUESTStat Priority#: Hit (9% cap) > Agility > Crit > AP > Ranged Weapon DPS" },
		}
	},

-----------Druid Talents
	[11014] = {
		title = "Druid - Leveling Talents",
		items = {
			[1] = { str = "#NPCDruid Leveling Build# - Feral Cat" },
			[2] = { str = "#DOQUESTRecommended Spec#: Feral for efficiency" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Ferocity 5/5 - Cheaper abilities" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Feral Aggression 5/5 - Ferocious Bite damage" },
			[5] = { str = "#DOQUESTLevel 20 (1 point)#: Feral Charge 1/1 - Gap closer!" },
			[6] = { str = "#DOQUESTLevel 21-25 (5 points)#: Sharpened Claws 3/3 + Predatory Strikes 2/3" },
			[7] = { str = "#DOQUESTLevel 26-29 (4 points)#: Finish Predatory Strikes 3/3 + Blood Frenzy 1/2" },
			[8] = { str = "#DOQUESTLevel 30 (1 point)#: Heart of the Wild 1/5" },
			[9] = { str = "#DOQUESTLevel 31-34 (4 points)#: Finish Heart of the Wild 5/5" },
			[10] = { str = "#DOQUESTLevel 35-39 (5 points)#: Savage Fury 2/2 + Faerie Fire (Feral) 1/1 + Feral Instinct 2/5" },
			[11] = { str = "#DOQUESTLevel 40 (1 point)#: Leader of the Pack 1/1 - Crit aura!" },
			[12] = { str = "#DOQUESTLevel 41-45 (5 points)#: Furor 5/5 (Restoration) - Energy on shift" },
			[13] = { str = "#DOQUESTLevel 46-50 (5 points)#: Naturalist 5/5 (Resto) - +10% melee damage" },
			[14] = { str = "#DOQUESTLevel 51-55 (5 points)#: Natural Shapeshifter 3/3 + Omen of Clarity 1/1 + 1 flex" },
			[15] = { str = "#DOQUESTLevel 56-60 (5 points)#: Improved Mark of the Wild 5/5" },
			[16] = { str = "#TURNINRotation#: Stealth > Ravage > Shred to 5 CP > Ferocious Bite. Keep Faerie Fire up. Use Tiger's Fury!" },
			[17] = { str = "#DOQUESTTips#: Powershift (shift out and in) to reset swing timer. Can heal yourself between pulls. Very flexible class!" },
		}
	},

	[11015] = {
		title = "Druid - Restoration (Raid)",
		items = {
			[1] = { str = "#NPCRestoration Druid Raid Healer#" },
			[2] = { str = "#DOQUESTSpec#: 24/0/27 or 8/11/32" },
			[3] = { str = "#DOQUESTBalance (8-24 points)#:" },
			[4] = { str = "#ACCEPT- Improved Mark of the Wild 5/5#" },
			[5] = { str = "#ACCEPT- Natural Weapons 5/5# (for 24-point build)" },
			[6] = { str = "#ACCEPT- Omen of Clarity 1/1# - Free spells!" },
			[7] = { str = "#ACCEPT- Natural Shapeshifter 3/3# (optional)" },
			[8] = { str = "#ACCEPT- (Deep Balance) Moonglow 5/5# - Cheaper heals" },
			[9] = { str = "#ACCEPT- (Deep Balance) Nature's Grace 1/1# - Haste on crit" },
			[10] = { str = "#DOQUESTRestoration (27-32 points)#:" },
			[11] = { str = "#ACCEPT- Furor 5/5# - Shift utility" },
			[12] = { str = "#ACCEPT- Improved Healing Touch 5/5# - Faster HT" },
			[13] = { str = "#ACCEPT- Reflection 3/3# - Mana regen" },
			[14] = { str = "#ACCEPT- Insect Swarm 1/1# - Tank survival" },
			[15] = { str = "#ACCEPT- Subtlety 5/5# - Threat reduction" },
			[16] = { str = "#ACCEPT- Tranquil Spirit 5/5# - Mana efficiency" },
			[17] = { str = "#ACCEPT- Improved Rejuvenation 3/3#" },
			[18] = { str = "#ACCEPT- Nature's Swiftness 1/1# - Instant cast!" },
			[19] = { str = "#ACCEPT- Gift of Nature 5/5# - +10% healing" },
			[20] = { str = "#ACCEPT- (Optional) Swiftmend 1/1# - Consume HoT for burst" },
			[21] = { str = "#TURNINHealing Style#: Rejuvenation blanketing on raid. Healing Touch on tanks. Innervate healers!" },
			[22] = { str = "#DOQUESTStat Priority#: +Healing > Spirit > Intellect > MP5" },
		}
	},

-----------Shaman Talents
	[11016] = {
		title = "Shaman - Leveling Talents",
		items = {
			[1] = { str = "#NPCShaman Leveling Build# - Enhancement" },
			[2] = { str = "#DOQUESTRecommended Spec#: Enhancement for melee" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Ancestral Knowledge 5/5 - Mana" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Thundering Strikes 5/5 - Crit" },
			[5] = { str = "#DOQUESTLevel 20-24 (5 points)#: Improved Ghost Wolf 2/2 + Flurry 3/5" },
			[6] = { str = "#DOQUESTLevel 25-26 (2 points)#: Finish Flurry 5/5" },
			[7] = { str = "#DOQUESTLevel 27-29 (3 points)#: Elemental Weapons 3/3 - Weapon enchants!" },
			[8] = { str = "#DOQUESTLevel 30 (1 point)#: Stormstrike 1/1 - THE ability!" },
			[9] = { str = "#DOQUESTLevel 31-35 (5 points)#: Weapon Mastery 5/5 - +10% damage" },
			[10] = { str = "#DOQUESTLevel 36-39 (4 points)#: Parry 1/1 + Toughness 3/5" },
			[11] = { str = "#DOQUESTLevel 40 (1 point)#: Two-Handed Axes/Maces 1/1 - Use 2H!" },
			[12] = { str = "#DOQUESTLevel 41-45 (5 points)#: Improved Lightning Shield 3/3 + Convection 2/5 (Elemental)" },
			[13] = { str = "#DOQUESTLevel 46-50 (5 points)#: Finish Convection 5/5 + Concussion 2/5" },
			[14] = { str = "#DOQUESTLevel 51-55 (5 points)#: Finish Concussion 5/5 + 2 points in Call of Flame" },
			[15] = { str = "#DOQUESTLevel 56-60 (5 points)#: Elemental Focus 1/1 + Eye of the Storm 3/3 + 1 flex" },
			[16] = { str = "#TURNINRotation#: Lightning Shield > Flame Shock > Earth Shock > Stormstrike > melee. Use Searing Totem!" },
			[17] = { str = "#DOQUESTTips#: Rockbiter until you get Windfury. WF procs are insane! Get a slow 2H weapon at 40." },
		}
	},

	[11017] = {
		title = "Shaman - Restoration (Raid)",
		items = {
			[1] = { str = "#NPCRestoration Shaman Raid Healer#" },
			[2] = { str = "#DOQUESTSpec#: 0/5/46" },
			[3] = { str = "#DOQUESTEnhancement (5 points)#:" },
			[4] = { str = "#ACCEPT- Ancestral Knowledge 5/5# - Mana pool" },
			[5] = { str = "#DOQUESTRestoration (46 points)#:" },
			[6] = { str = "#ACCEPT- Improved Healing Wave 5/5# - Faster HW" },
			[7] = { str = "#ACCEPT- Tidal Focus 5/5# - Cheaper heals" },
			[8] = { str = "#ACCEPT- Improved Reincarnation 2/2# - Ankh utility" },
			[9] = { str = "#ACCEPT- Totemic Focus 5/5# - Cheaper totems" },
			[10] = { str = "#ACCEPT- Healing Focus 5/5# - No pushback" },
			[11] = { str = "#ACCEPT- Totemic Mastery 1/1# - Totem range" },
			[12] = { str = "#ACCEPT- Healing Grace 3/3# - Threat reduction" },
			[13] = { str = "#ACCEPT- Restorative Totems 5/5# - Mana Spring/Healing Stream" },
			[14] = { str = "#ACCEPT- Tidal Mastery 5/5# - Crit heals" },
			[15] = { str = "#ACCEPT- Nature's Swiftness 1/1# - Instant cast!" },
			[16] = { str = "#ACCEPT- Purification 5/5# - +10% healing" },
			[17] = { str = "#ACCEPT- Mana Tide Totem 1/1# - Raid mana!" },
			[18] = { str = "#TURNINHealing Style#: Chain Heal is your bread and butter. Lesser Healing Wave for tank. Mana Tide for healers!" },
			[19] = { str = "#DOQUESTTotems#: Always drop: Mana Spring, Strength of Earth (or Stoneskin), Windfury (melee group), Grace of Air (ranged)" },
			[20] = { str = "#DOQUESTStat Priority#: +Healing > MP5 > Intellect > Spirit" },
		}
	},

-----------Paladin Talents
	[11018] = {
		title = "Paladin - Leveling Talents",
		items = {
			[1] = { str = "#NPCPaladin Leveling Build# - Retribution" },
			[2] = { str = "#DOQUESTRecommended Spec#: Retribution all the way!" },
			[3] = { str = "#DOQUESTLevel 10-14 (5 points)#: Benediction 5/5 - Cheaper seals" },
			[4] = { str = "#DOQUESTLevel 15-19 (5 points)#: Improved Judgement 2/2 + Improved Seal of the Crusader 3/3" },
			[5] = { str = "#DOQUESTLevel 20-24 (5 points)#: Deflection 5/5 - Parry" },
			[6] = { str = "#DOQUESTLevel 25-29 (5 points)#: Conviction 5/5 - 5% crit" },
			[7] = { str = "#DOQUESTLevel 30 (1 point)#: Seal of Command 1/1 - THE leveling ability!" },
			[8] = { str = "#DOQUESTLevel 31-35 (5 points)#: Pursuit of Justice 2/2 + Eye for an Eye 2/2 + 1 point flex" },
			[9] = { str = "#DOQUESTLevel 36-39 (4 points)#: Two-Handed Weapon Specialization 3/3 + Sanctity Aura 1/1" },
			[10] = { str = "#DOQUESTLevel 40 (1 point)#: Vengeance 1/5 (or Repentance 1/1 for PvP)" },
			[11] = { str = "#DOQUESTLevel 41-45 (5 points)#: Finish Vengeance 5/5 (in Ret)" },
			[12] = { str = "#DOQUESTLevel 46-50 (5 points)#: Divine Strength 5/5 (Protection tree)" },
			[13] = { str = "#DOQUESTLevel 51-55 (5 points)#: Divine Intellect 5/5 (Holy tree)" },
			[14] = { str = "#DOQUESTLevel 56-60 (5 points)#: Spiritual Focus 5/5 (Holy) - Healing doesn't get interrupted" },
			[15] = { str = "#TURNINRotation#: Judge SotC > Seal of Command > Auto attack > Judge when off CD. Use Consecration if mana allows." },
			[16] = { str = "#DOQUESTTips#: Get a SLOW 2H weapon (3.5+ speed). SoC procs based on weapon speed. Blessing of Wisdom while grinding." },
		}
	},

	[11019] = {
		title = "Paladin - Holy Healer (Raid)",
		items = {
			[1] = { str = "#NPCHoly Paladin Raid Healer#" },
			[2] = { str = "#DOQUESTSpec#: 31/20/0 or 35/11/5" },
			[3] = { str = "#DOQUESTHoly (31-35 points)#:" },
			[4] = { str = "#ACCEPT- Divine Strength 5/5# - Strength for block" },
			[5] = { str = "#ACCEPT- Divine Intellect 5/5# - Mana" },
			[6] = { str = "#ACCEPT- Spiritual Focus 5/5# - No pushback" },
			[7] = { str = "#ACCEPT- Improved Lay on Hands 2/2#" },
			[8] = { str = "#ACCEPT- Healing Light 3/3# - +12% healing" },
			[9] = { str = "#ACCEPT- Consecration 1/1# (useful for dungeons)" },
			[10] = { str = "#ACCEPT- Illumination 5/5# - Mana refund on crit!" },
			[11] = { str = "#ACCEPT- Divine Favor 1/1# - Guaranteed crit" },
			[12] = { str = "#ACCEPT- Lasting Judgement 3/3# (or Holy Power)" },
			[13] = { str = "#ACCEPT- Holy Power 5/5# - Crit chance" },
			[14] = { str = "#ACCEPT- Holy Shock 1/1# - Instant heal" },
			[15] = { str = "#DOQUESTProtection (11-20 points)#:" },
			[16] = { str = "#ACCEPT- Improved Devotion Aura 5/5#" },
			[17] = { str = "#ACCEPT- Precision 3/3# - Hit for Judgements" },
			[18] = { str = "#ACCEPT- Guardian's Favor 2/2#" },
			[19] = { str = "#ACCEPT- Toughness 5/5# - Armor" },
			[20] = { str = "#ACCEPT- (Optional) Blessing of Kings 1/1# - Raid buff!" },
			[21] = { str = "#TURNINHealing Style#: Flash of Light spam (very mana efficient). Use Holy Light for big damage. Divine Favor + HS for emergencies." },
			[22] = { str = "#DOQUESTStat Priority#: +Healing > Intellect > Crit > MP5" },
		}
	},
}
