--[[--------------------------------------------------
009_GearGuides.lua
Authors: theKennethy
Version: 1.05.0
------------------------------------------------------
Description: Gear & Upgrade Guides for Vanilla WoW
    - Pre-raid BiS lists
    - Leveling upgrades
    - Class-specific gear recommendations
------------------------------------------------------
]]--

Table_009_GearGuides = {
-----------General Gearing Guide
	[12001] = {
		title = "Gearing Guide - Overview",
		items = {
			[1] = { str = "#NPCGearing in Vanilla WoW# - Understanding Stats" },
			[2] = { str = "#DOQUESTStat Priority by Role#:" },
			[3] = { str = "#ACCEPTMelee DPS#: Hit (cap) > Crit > AP/Strength > Agility" },
			[4] = { str = "#ACCEPTCaster DPS#: Hit (16% cap) > Spell Power > Crit > Intellect" },
			[5] = { str = "#ACCEPTHealers#: +Healing > MP5/Spirit > Intellect > Stamina" },
			[6] = { str = "#ACCEPTTanks#: Defense (440 cap) > Stamina > Armor > Dodge/Parry" },
			[7] = { str = "#DOQUESTHit Caps#:" },
			[8] = { str = "#TURNIN- Melee (Yellow/Special)#: 9% (or 6% with +5 weapon skill)" },
			[9] = { str = "#TURNIN- Melee (White/Auto)#: 24.6% dual wield, 9% 2H" },
			[10] = { str = "#TURNIN- Caster#: 16% vs bosses (17% if not same school)" },
			[11] = { str = "#TURNIN- Hunter#: 9% with ranged" },
			[12] = { str = "#DOQUESTDefense Cap#: 440 for tanks (uncrittable vs 63 boss)" },
			[13] = { str = "#DOQUESTWhere to Get Gear#:" },
			[14] = { str = "#ACCEPT- Dungeons#: 5-mans drop blues, pre-raid BiS" },
			[15] = { str = "#ACCEPT- Crafting#: Some BiS items are crafted" },
			[16] = { str = "#ACCEPT- PvP#: Rank 10+ gear is strong" },
			[17] = { str = "#ACCEPT- World Drops#: BoE epics (expensive!)" },
			[18] = { str = "#ACCEPT- Reputation#: Some factions give gear rewards" },
		}
	},

-----------Warrior Gear
	[12002] = {
		title = "Warrior - Pre-Raid BiS (Fury DPS)",
		items = {
			[1] = { str = "#NPCFury Warrior Pre-Raid BiS#" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Lionheart Helm# (Crafted BS) - THE BiS, expensive but BiS until Naxx" },
			[4] = { str = "#ACCEPT- Mask of the Unforgiven# (Strat Live) - Budget option" },
			[5] = { str = "#DOQUESTNeck#:" },
			[6] = { str = "#ACCEPT- Mark of Fordring# (Quest: In Dreams, EPL) - Free and great" },
			[7] = { str = "#ACCEPT- Imperial Jewel# (BRD Emperor) - Alternative" },
			[8] = { str = "#DOQUESTShoulders#:" },
			[9] = { str = "#ACCEPT- Truestrike Shoulders# (UBRS Rend) - BiS until AQ40" },
			[10] = { str = "#ACCEPT- Wyrmhide Spaulders# (UBRS) - Budget option" },
			[11] = { str = "#DOQUESTBack#:" },
			[12] = { str = "#ACCEPT- Cape of the Black Baron# (Strat UD Baron) - Best" },
			[13] = { str = "#ACCEPT- Stoneskin Gargoyle Cape# (Strat UD) - Alternative" },
			[14] = { str = "#DOQUESTChest#:" },
			[15] = { str = "#ACCEPT- Savage Gladiator Chain# (BRD Arena) - Amazing chest" },
			[16] = { str = "#ACCEPT- Cadaverous Armor# (Scholo) - Plate option" },
			[17] = { str = "#DOQUESTWrists#:" },
			[18] = { str = "#ACCEPT- Battleborn Armbraces# (Strat UD) - Best" },
			[19] = { str = "#ACCEPT- Vambraces of the Sadist# (Strat Live) - Alternative" },
			[20] = { str = "#DOQUESTHands#:" },
			[21] = { str = "#ACCEPT- Devilsaur Gauntlets# (Crafted LW) - BiS set piece" },
			[22] = { str = "#ACCEPT- Edgemaster's Handguards# (World Drop) - If not Human/Orc, very expensive" },
			[23] = { str = "#DOQUESTWaist#:" },
			[24] = { str = "#ACCEPT- Brigam Girdle# (UBRS Drakkisath) - Best" },
			[25] = { str = "#ACCEPT- Omokk's Girth Restrainer# (LBRS) - Alternative" },
			[26] = { str = "#DOQUESTLegs#:" },
			[27] = { str = "#ACCEPT- Devilsaur Leggings# (Crafted LW) - BiS set piece" },
			[28] = { str = "#ACCEPT- Cloudkeeper Legplates# (World Drop) - Very expensive" },
			[29] = { str = "#DOQUESTFeet#:" },
			[30] = { str = "#ACCEPT- Battlechaser's Greaves# (Quest: General Drakkisath's Demise) - Free!" },
			[31] = { str = "#ACCEPT- Bloodmail Boots# (Scholo) - Alternative" },
			[32] = { str = "#DOQUESTRings#:" },
			[33] = { str = "#ACCEPT- Don Julio's Band# (AV Exalted) - Very good" },
			[34] = { str = "#ACCEPT- Blackstone Ring# (Maraudon Princess) - Easy to get" },
			[35] = { str = "#ACCEPT- Painweaver Band# (UBRS Beast) - Great ring" },
			[36] = { str = "#DOQUESTTrinkets#:" },
			[37] = { str = "#ACCEPT- Blackhand's Breadth# (UBRS quest) - BiS" },
			[38] = { str = "#ACCEPT- Hand of Justice# (BRD Emperor/Arena) - BiS for melee" },
			[39] = { str = "#DOQUESTWeapons#:" },
			[40] = { str = "#ACCEPT- Dal'Rend's Set# (UBRS Rend) - MH + OH swords, BiS pre-raid" },
			[41] = { str = "#ACCEPT- Chromatically Tempered Sword# (BWL trash/crafted) - Later option" },
			[42] = { str = "#ACCEPT- Mirah's Song# (Quest: Scholo) - Free good sword" },
		}
	},

	[12003] = {
		title = "Warrior - Pre-Raid BiS (Prot Tank)",
		items = {
			[1] = { str = "#NPCProtection Warrior Pre-Raid BiS#" },
			[2] = { str = "#DOQUESTGoal#: 440 Defense, then stack Stamina and Armor" },
			[3] = { str = "#DOQUESTHead#:" },
			[4] = { str = "#ACCEPT- Golem Skull Helm# (BRD Golem Lord) - Best" },
			[5] = { str = "#ACCEPT- Helm of the Holy Avenger# (Strat Live) - Alternative" },
			[6] = { str = "#DOQUESTNeck#:" },
			[7] = { str = "#ACCEPT- Amulet of the Darkmoon# (Darkmoon Faire) - Best early" },
			[8] = { str = "#ACCEPT- Medallion of Grand Marshal Morris# (Quest) - +10 Defense" },
			[9] = { str = "#DOQUESTShoulders#:" },
			[10] = { str = "#ACCEPT- Stockade Pauldrons# (BRD Arena/Golem) - Best" },
			[11] = { str = "#ACCEPT- Spaulders of Valor# (LBRS T0) - Dungeon set" },
			[12] = { str = "#DOQUESTBack#:" },
			[13] = { str = "#ACCEPT- Stoneshield Cloak# (BRD) - Armor" },
			[14] = { str = "#ACCEPT- Redoubt Cloak# (Quest: Tirion Fordring chain) - Defense" },
			[15] = { str = "#DOQUESTChest#:" },
			[16] = { str = "#ACCEPT- Deathbone Chestplate# (Scholo) - Defense set" },
			[17] = { str = "#ACCEPT- Breastplate of Valor# (UD Strat T0) - Dungeon set" },
			[18] = { str = "#DOQUESTWrists#:" },
			[19] = { str = "#ACCEPT- Hands of the Exalted Herald# (Strat UD) - Defense" },
			[20] = { str = "#ACCEPT- Bracers of Valor# (LBRS T0) - Dungeon set" },
			[21] = { str = "#DOQUESTHands#:" },
			[22] = { str = "#ACCEPT- Gauntlets of Valor# (BRS T0) - Dungeon set" },
			[23] = { str = "#ACCEPT- Flameguard Gauntlets# (BRD) - FR tank option" },
			[24] = { str = "#DOQUESTWaist#:" },
			[25] = { str = "#ACCEPT- Deathbone Girdle# (Scholo) - Defense set" },
			[26] = { str = "#ACCEPT- Girdle of the Dawn# (AD Revered) - Farm this!" },
			[27] = { str = "#DOQUESTLegs#:" },
			[28] = { str = "#ACCEPT- Deathbone Legguards# (Scholo) - Defense set" },
			[29] = { str = "#ACCEPT- Legplates of Valor# (Strat Live T0) - Dungeon set" },
			[30] = { str = "#DOQUESTFeet#:" },
			[31] = { str = "#ACCEPT- Deathbone Sabatons# (Scholo) - Defense set" },
			[32] = { str = "#ACCEPT- Boots of Valor# (BRS T0) - Dungeon set" },
			[33] = { str = "#DOQUESTShield#:" },
			[34] = { str = "#ACCEPT- Skullflame Shield# (World Drop) - BiS but expensive" },
			[35] = { str = "#ACCEPT- Draconian Deflector# (UBRS Rend) - Solid shield" },
			[36] = { str = "#ACCEPT- Argent Defender# (AD Honored) - Easy to get" },
			[37] = { str = "#DOQUESTWeapon#:" },
			[38] = { str = "#ACCEPT- Quel'Serrar# (Quest: Dire Maul Book + Onyxia) - THE tank weapon!" },
			[39] = { str = "#ACCEPT- Mirah's Song# (Quest: Scholo) - Free option" },
			[40] = { str = "#ACCEPT- Alcor's Sunrazor# (World Drop) - Fast threat option" },
			[41] = { str = "#DOQUESTTrinkets#:" },
			[42] = { str = "#ACCEPT- Mark of the Chosen# (Mara Princess quest) - Proc is great" },
			[43] = { str = "#ACCEPT- Force of Will# (BRD Emperor) - Stamina + absorb" },
		}
	},

-----------Rogue Gear
	[12004] = {
		title = "Rogue - Pre-Raid BiS",
		items = {
			[1] = { str = "#NPCRogue Pre-Raid BiS# (Combat Daggers/Swords)" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Mask of the Unforgiven# (Strat Live) - Best" },
			[4] = { str = "#ACCEPT- Shadowcraft Cap# (Scholo T0) - Dungeon set" },
			[5] = { str = "#DOQUESTNeck#:" },
			[6] = { str = "#ACCEPT- Mark of Fordring# (Quest: In Dreams) - Free!" },
			[7] = { str = "#ACCEPT- Imperial Jewel# (BRD Emperor) - Alternative" },
			[8] = { str = "#DOQUESTShoulders#:" },
			[9] = { str = "#ACCEPT- Truestrike Shoulders# (UBRS) - BiS until AQ" },
			[10] = { str = "#ACCEPT- Shadowcraft Spaulders# (LBRS T0) - Budget" },
			[11] = { str = "#DOQUESTBack#:" },
			[12] = { str = "#ACCEPT- Cape of the Black Baron# (Strat UD Baron)" },
			[13] = { str = "#DOQUESTChest#:" },
			[14] = { str = "#ACCEPT- Cadaverous Armor# (Scholo) - Great chest" },
			[15] = { str = "#ACCEPT- Nightbrace Tunic# (Strat UD) - Alternative" },
			[16] = { str = "#DOQUESTWrists#:" },
			[17] = { str = "#ACCEPT- Bracers of the Eclipse# (Scholo) - BiS" },
			[18] = { str = "#DOQUESTHands#:" },
			[19] = { str = "#ACCEPT- Devilsaur Gauntlets# (Crafted LW) - BiS" },
			[20] = { str = "#DOQUESTWaist#:" },
			[21] = { str = "#ACCEPT- Mugger's Belt# (BRD Arena) - Best" },
			[22] = { str = "#ACCEPT- Brigam Girdle# if needed for hit" },
			[23] = { str = "#DOQUESTLegs#:" },
			[24] = { str = "#ACCEPT- Devilsaur Leggings# (Crafted LW) - BiS" },
			[25] = { str = "#DOQUESTFeet#:" },
			[26] = { str = "#ACCEPT- Swiftwalker Boots# (DM East) - BiS" },
			[27] = { str = "#ACCEPT- Shadowcraft Boots# (Strat Live T0) - Alternative" },
			[28] = { str = "#DOQUESTRings#:" },
			[29] = { str = "#ACCEPT- Don Julio's Band# (AV Exalted)" },
			[30] = { str = "#ACCEPT- Painweaver Band# (UBRS Beast)" },
			[31] = { str = "#ACCEPT- Tarnished Elven Ring# (DM West/North)" },
			[32] = { str = "#DOQUESTTrinkets#:" },
			[33] = { str = "#ACCEPT- Blackhand's Breadth# (UBRS quest) - BiS" },
			[34] = { str = "#ACCEPT- Hand of Justice# (BRD Arena/Emperor) - BiS" },
			[35] = { str = "#DOQUESTWeapons (Daggers)#:" },
			[36] = { str = "#ACCEPT- Felstriker# (UBRS Anvilcrack, rare) - Dream weapon!" },
			[37] = { str = "#ACCEPT- Alcor's Sunrazor# (World Drop) - Fast dagger" },
			[38] = { str = "#ACCEPT- Heartseeker# (Crafted BS) - Solid main hand" },
			[39] = { str = "#ACCEPT- Distracting Dagger# (BRD Plugger) - Fast off hand" },
			[40] = { str = "#DOQUESTWeapons (Swords)#:" },
			[41] = { str = "#ACCEPT- Dal'Rend's Set# (UBRS Rend) - MH + OH" },
			[42] = { str = "#ACCEPT- Thrash Blade# (Quest: Maraudon) - Extra attacks!" },
		}
	},

-----------Mage Gear
	[12005] = {
		title = "Mage - Pre-Raid BiS",
		items = {
			[1] = { str = "#NPCMage Pre-Raid BiS# - Hit > SP > Crit" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Spellweaver's Turban# (Scholo Gandling) - Best" },
			[4] = { str = "#ACCEPT- Crimson Felt Hat# (Strat Live Cannon Master)" },
			[5] = { str = "#DOQUESTNeck#:" },
			[6] = { str = "#ACCEPT- Choker of the Fire Lord# (MC Ragnaros) - Later BiS" },
			[7] = { str = "#ACCEPT- Star of Mystaria# (Quest: BRD/Ony chain) - Great free option" },
			[8] = { str = "#DOQUESTShoulders#:" },
			[9] = { str = "#ACCEPT- Boreal Mantle# (DM North Tribute) - BiS" },
			[10] = { str = "#ACCEPT- Kentic Amice# (BRD Incendius) - Alternative" },
			[11] = { str = "#DOQUESTBack#:" },
			[12] = { str = "#ACCEPT- Sapphiron Drape# (Scholo) - Best if not hit capped" },
			[13] = { str = "#ACCEPT- Archivist Cape# (Strat Live) - +1% hit!" },
			[14] = { str = "#DOQUESTChest#:" },
			[15] = { str = "#ACCEPT- Robe of the Archmage# (Crafted Tailoring) - BiS until BWL" },
			[16] = { str = "#ACCEPT- Robe of Winter Night# (Crafted) - Alternative" },
			[17] = { str = "#DOQUESTWrists#:" },
			[18] = { str = "#ACCEPT- Bracers of Arcane Accuracy# (World Drop) - +1% hit" },
			[19] = { str = "#ACCEPT- Sublime Wristguards# (Strat UD) - SP option" },
			[20] = { str = "#DOQUESTHands#:" },
			[21] = { str = "#ACCEPT- Hands of Power# (LBRS Quartermaster) - +1% hit!" },
			[22] = { str = "#ACCEPT- Magister's Gloves# (DM West T0) - Alternative" },
			[23] = { str = "#DOQUESTWaist#:" },
			[24] = { str = "#ACCEPT- Mana Igniting Cord# (World drop) - BiS, expensive" },
			[25] = { str = "#ACCEPT- Ban'thok Sash# (BRD Arena) - Budget option" },
			[26] = { str = "#DOQUESTLegs#:" },
			[27] = { str = "#ACCEPT- Skyshroud Leggings# (LBRS Omokk) - Hit!" },
			[28] = { str = "#ACCEPT- Flarecore Leggings# (Crafted) - Fire spec BiS" },
			[29] = { str = "#DOQUESTFeet#:" },
			[30] = { str = "#ACCEPT- Omnicast Boots# (DM West Immol'thar) - BiS" },
			[31] = { str = "#ACCEPT- Magister's Boots# (UBRS T0) - Alternative" },
			[32] = { str = "#DOQUESTRings#:" },
			[33] = { str = "#ACCEPT- Freezing Band# (World Drop, expensive)" },
			[34] = { str = "#ACCEPT- Eye of Orgrimmar# (World Drop, Horde)" },
			[35] = { str = "#ACCEPT- Songstone of Ironforge# (World Drop, Alliance)" },
			[36] = { str = "#ACCEPT- Ring of Spell Power# (MC trash)" },
			[37] = { str = "#DOQUESTTrinkets#:" },
			[38] = { str = "#ACCEPT- Briarwood Reed# (UBRS Jed quest) - +crit" },
			[39] = { str = "#ACCEPT- Eye of the Beast# (UBRS Beast) - On use" },
			[40] = { str = "#DOQUESTWeapon#:" },
			[41] = { str = "#ACCEPT- Headmaster's Charge# (Scholo Gandling) - BiS staff until AQ" },
			[42] = { str = "#ACCEPT- Witchblade# (Scholo) + Drakestone# (UBRS) - 1H + OH option" },
			[43] = { str = "#DOQUESTWand#:" },
			[44] = { str = "#ACCEPT- Bonecreeper Stylus# (Scholo) - BiS" },
			[45] = { str = "#ACCEPT- Ritssyn's Wand of Bad Mojo# (World drop)" },
		}
	},

-----------Healer Gear (Priest/Druid/Shaman/Paladin shared)
	[12006] = {
		title = "Healer - Pre-Raid BiS",
		items = {
			[1] = { str = "#NPCHealer Pre-Raid BiS# - +Healing focused" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Cassandra's Grace# (World Drop) - +75 healing, expensive" },
			[4] = { str = "#ACCEPT- Devout Crown# (Strat Live T0) - Priest" },
			[5] = { str = "#ACCEPT- Whitesoul Helm# (Crafted) - Paladin" },
			[6] = { str = "#DOQUESTNeck#:" },
			[7] = { str = "#ACCEPT- Animated Chain Necklace# (Strat UD Ramstein)" },
			[8] = { str = "#ACCEPT- Orb of the Darkmoon# (Darkmoon Faire deck)" },
			[9] = { str = "#DOQUESTShoulders#:" },
			[10] = { str = "#ACCEPT- Living Shoulders# (DM East Alzzin) - BiS +healing" },
			[11] = { str = "#ACCEPT- Burial Shawl# (Scholo) - Alternative" },
			[12] = { str = "#DOQUESTBack#:" },
			[13] = { str = "#ACCEPT- Hide of the Wild# (Crafted LW) - BiS pre-raid" },
			[14] = { str = "#ACCEPT- Amplifying Cloak# (Strat UD) - Budget" },
			[15] = { str = "#DOQUESTChest#:" },
			[16] = { str = "#ACCEPT- Truefaith Vestments# (Crafted Tailoring) - BiS until Naxx!" },
			[17] = { str = "#ACCEPT- Robes of the Exalted# (Strat Live) - Alternative" },
			[18] = { str = "#DOQUESTWrists#:" },
			[19] = { str = "#ACCEPT- Loomguard Armbraces# (Scholo) - Best" },
			[20] = { str = "#ACCEPT- Bracers of Prosperity# (DM North Tribute)" },
			[21] = { str = "#DOQUESTHands#:" },
			[22] = { str = "#ACCEPT- Harmonious Gauntlets# (Strat UD) - BiS" },
			[23] = { str = "#ACCEPT- Devout Gloves# (Scholo T0) - Priest" },
			[24] = { str = "#DOQUESTWaist#:" },
			[25] = { str = "#ACCEPT- Whipvine Cord# (DM East) - BiS" },
			[26] = { str = "#ACCEPT- Sash of Mercy# (BRD) - Alternative" },
			[27] = { str = "#DOQUESTLegs#:" },
			[28] = { str = "#ACCEPT- Padre's Trousers# (Strat Live) - BiS +healing" },
			[29] = { str = "#ACCEPT- Devout Skirt# (LBRS/Scholo T0) - Priest" },
			[30] = { str = "#DOQUESTFeet#:" },
			[31] = { str = "#ACCEPT- Boots of the Full Moon# (DM West Illyana) - Druid BiS" },
			[32] = { str = "#ACCEPT- Devout Sandals# (Strat Live T0) - Priest" },
			[33] = { str = "#DOQUESTRings#:" },
			[34] = { str = "#ACCEPT- Fordring's Seal# (Quest: In Dreams chain) - Free!" },
			[35] = { str = "#ACCEPT- Rosewine Circle# (BRD) - +healing" },
			[36] = { str = "#ACCEPT- Second Wind# (DM West) - Good stats" },
			[37] = { str = "#DOQUESTTrinkets#:" },
			[38] = { str = "#ACCEPT- Shard of the Scale# (Onyxia) - BiS MP5" },
			[39] = { str = "#ACCEPT- Royal Seal of Eldre'Thalas# (DM class books) - +healing on use" },
			[40] = { str = "#ACCEPT- Second Wind# (BRD) - Mana restore" },
			[41] = { str = "#DOQUESTWeapon#:" },
			[42] = { str = "#ACCEPT- Benediction/Anathema# (MC quest) - Priest BiS" },
			[43] = { str = "#ACCEPT- Hammer of Grace# (Strat UD) - 1H + shield option" },
			[44] = { str = "#ACCEPT- The Hammer of Grace# + Thaurissan's Royal Scepter# (BRD Emperor)" },
			[45] = { str = "#DOQUESTOff-Hand/Shield#:" },
			[46] = { str = "#ACCEPT- Drakestone of Healing# (UBRS Rend) - Off-hand" },
			[47] = { str = "#ACCEPT- Aegis of the Scarlet Commander# (SM Cath) - Pally/Shaman" },
		}
	},

-----------Hunter Gear
	[12007] = {
		title = "Hunter - Pre-Raid BiS",
		items = {
			[1] = { str = "#NPCHunter Pre-Raid BiS# - Hit > Agi > AP > Crit" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Beaststalker's Cap# (Scholo T0) - Dungeon set" },
			[4] = { str = "#ACCEPT- Mask of the Unforgiven# (Strat Live) - great stats" },
			[5] = { str = "#DOQUESTNeck#:" },
			[6] = { str = "#ACCEPT- Mark of Fordring# (Quest: In Dreams) - Free!" },
			[7] = { str = "#DOQUESTShoulders#:" },
			[8] = { str = "#ACCEPT- Truestrike Shoulders# (UBRS) - BiS" },
			[9] = { str = "#ACCEPT- Beaststalker's Mantle# (UBRS T0)" },
			[10] = { str = "#DOQUESTBack#:" },
			[11] = { str = "#ACCEPT- Cape of the Black Baron# (Strat UD Baron)" },
			[12] = { str = "#ACCEPT- Cloak of Warding# (DM North) - Agility" },
			[13] = { str = "#DOQUESTChest#:" },
			[14] = { str = "#ACCEPT- Savage Gladiator Chain# (BRD Arena) - BiS" },
			[15] = { str = "#ACCEPT- Beaststalker's Tunic# (UBRS T0)" },
			[16] = { str = "#DOQUESTWrists#:" },
			[17] = { str = "#ACCEPT- Bracer of the Eclipse# (Scholo) - Best" },
			[18] = { str = "#ACCEPT- Slashclaw Bracers# (LBRS) - Alternative" },
			[19] = { str = "#DOQUESTHands#:" },
			[20] = { str = "#ACCEPT- Devilsaur Gauntlets# (Crafted LW) - BiS" },
			[21] = { str = "#ACCEPT- Beaststalker's Gloves# (Strat Live T0)" },
			[22] = { str = "#DOQUESTWaist#:" },
			[23] = { str = "#ACCEPT- Marksman's Girdle# (DM North Gordok) - Best" },
			[24] = { str = "#ACCEPT- Beaststalker's Belt# (BRD T0)" },
			[25] = { str = "#DOQUESTLegs#:" },
			[26] = { str = "#ACCEPT- Devilsaur Leggings# (Crafted LW) - BiS" },
			[27] = { str = "#ACCEPT- Beaststalker's Pants# (LBRS T0)" },
			[28] = { str = "#DOQUESTFeet#:" },
			[29] = { str = "#ACCEPT- Windreaver Greaves# (World Drop)" },
			[30] = { str = "#ACCEPT- Beaststalker's Boots# (Scholo T0)" },
			[31] = { str = "#DOQUESTRings#:" },
			[32] = { str = "#ACCEPT- Don Julio's Band# (AV Exalted)" },
			[33] = { str = "#ACCEPT- Painweaver Band# (UBRS Beast)" },
			[34] = { str = "#ACCEPT- Tarnished Elven Ring# (DM North/West)" },
			[35] = { str = "#DOQUESTTrinkets#:" },
			[36] = { str = "#ACCEPT- Blackhand's Breadth# (UBRS quest) - BiS" },
			[37] = { str = "#ACCEPT- Royal Seal of Eldre'Thalas# (DM Hunter book)" },
			[38] = { str = "#DOQUESTRanged Weapon#:" },
			[39] = { str = "#ACCEPT- Carapace Spine Crossbow# (BWL) - Later BiS" },
			[40] = { str = "#ACCEPT- Blackcrow# (LBRS Voone) - Great pre-raid" },
			[41] = { str = "#ACCEPT- Bloodseeker# (World drop) - Good bow" },
			[42] = { str = "#ACCEPT- Flawless Arcanite Rifle# (Engineering) - Good gun" },
			[43] = { str = "#DOQUESTMelee (Stat sticks)#:" },
			[44] = { str = "#ACCEPT- Bone Slicing Hatchet# (Strat UD) - Great stats" },
			[45] = { str = "#ACCEPT- Barbarous Blade# (DM North King) - 2H option" },
		}
	},

-----------Warlock Gear
	[12008] = {
		title = "Warlock - Pre-Raid BiS",
		items = {
			[1] = { str = "#NPCWarlock Pre-Raid BiS# - Hit > SP > Crit > Stamina" },
			[2] = { str = "#DOQUESTHead#:" },
			[3] = { str = "#ACCEPT- Spellweaver's Turban# (Scholo Gandling) - Same as Mage" },
			[4] = { str = "#ACCEPT- Deathmist Mask# (Scholo T0) - Dungeon set" },
			[5] = { str = "#DOQUESTNeck#:" },
			[6] = { str = "#ACCEPT- Star of Mystaria# (Quest: BRD/Ony chain)" },
			[7] = { str = "#ACCEPT- Choker of Enlightenment# (Scholo)" },
			[8] = { str = "#DOQUESTShoulders#:" },
			[9] = { str = "#ACCEPT- Felcloth Shoulders# (Crafted Tailoring) - BiS" },
			[10] = { str = "#ACCEPT- Kentic Amice# (BRD Incendius)" },
			[11] = { str = "#DOQUESTBack#:" },
			[12] = { str = "#ACCEPT- Sapphiron Drape# (Scholo) - Hit!" },
			[13] = { str = "#ACCEPT- Amplifying Cloak# (Strat UD)" },
			[14] = { str = "#DOQUESTChest#:" },
			[15] = { str = "#ACCEPT- Robe of the Void# (Crafted Tailoring) - BiS Warlock" },
			[16] = { str = "#ACCEPT- Robe of Winter Night# (Crafted) - Alternative" },
			[17] = { str = "#DOQUESTWrists#:" },
			[18] = { str = "#ACCEPT- Bracers of Arcane Accuracy# (World drop) - +1% hit" },
			[19] = { str = "#ACCEPT- Deathmist Bracers# (LBRS T0)" },
			[20] = { str = "#DOQUESTHands#:" },
			[21] = { str = "#ACCEPT- Hands of Power# (LBRS) - +1% hit" },
			[22] = { str = "#ACCEPT- Felcloth Gloves# (Crafted Tailoring) - Shadow damage" },
			[23] = { str = "#DOQUESTWaist#:" },
			[24] = { str = "#ACCEPT- Mana Igniting Cord# (World drop) - BiS, expensive" },
			[25] = { str = "#ACCEPT- Ban'thok Sash# (BRD Arena)" },
			[26] = { str = "#DOQUESTLegs#:" },
			[27] = { str = "#ACCEPT- Felcloth Pants# (Crafted Tailoring) - Shadow damage" },
			[28] = { str = "#ACCEPT- Skyshroud Leggings# (LBRS) - Hit" },
			[29] = { str = "#DOQUESTFeet#:" },
			[30] = { str = "#ACCEPT- Omnicast Boots# (DM West) - BiS" },
			[31] = { str = "#ACCEPT- Deathmist Sandals# (Scholo T0)" },
			[32] = { str = "#DOQUESTRings#:" },
			[33] = { str = "#ACCEPT- Ring of Spell Power# (MC trash)" },
			[34] = { str = "#ACCEPT- Freezing Band# (World drop) - SP" },
			[35] = { str = "#ACCEPT- Blackstone Ring# (Mara Princess)" },
			[36] = { str = "#DOQUESTTrinkets#:" },
			[37] = { str = "#ACCEPT- Briarwood Reed# (UBRS Jed quest)" },
			[38] = { str = "#ACCEPT- Eye of the Beast# (UBRS Beast)" },
			[39] = { str = "#DOQUESTWeapon#:" },
			[40] = { str = "#ACCEPT- Headmaster's Charge# (Scholo) - BiS staff" },
			[41] = { str = "#ACCEPT- Rod of the Ogre Magi# (DM North Tribute) - Good staff" },
			[42] = { str = "#DOQUESTWand#:" },
			[43] = { str = "#ACCEPT- Bonecreeper Stylus# (Scholo) - Shadow damage" },
			[44] = { str = "#ACCEPT- Skul's Ghastly Touch# (Strat UD Skul rare)" },
		}
	},

-----------Leveling Gear Upgrades
	[12009] = {
		title = "Leveling Gear - Key Upgrades",
		items = {
			[1] = { str = "#NPCKey Gear Upgrades While Leveling#" },
			[2] = { str = "#DOQUESTLevel 10-20 Weapons#:" },
			[3] = { str = "#ACCEPT- Vendetta# (Deadmines) - Dagger" },
			[4] = { str = "#ACCEPT- Smite's Mighty Hammer# (Deadmines) - 2H Mace" },
			[5] = { str = "#ACCEPT- Crescent Staff# (Wailing Caverns) - Staff" },
			[6] = { str = "#ACCEPT- Stinging Viper# (WC) - Dagger" },
			[7] = { str = "#DOQUESTLevel 20-30 Weapons#:" },
			[8] = { str = "#ACCEPT- Corpsemaker# (RFK Agathelos) - 2H Axe, incredible!" },
			[9] = { str = "#ACCEPT- Sword of Serenity# (Quest, Alliance) - Good 1H" },
			[10] = { str = "#ACCEPT- Staff of Westfall# (Deadmines quest) - Caster staff" },
			[11] = { str = "#ACCEPT- Meteor Shard# (SFK Arugal) - Caster sword" },
			[12] = { str = "#DOQUESTLevel 30-40 Weapons#:" },
			[13] = { str = "#ACCEPT- Ravager# (SM Armory Herod) - 2H Axe, AoE god!" },
			[14] = { str = "#ACCEPT- Mograine's Might# (SM Cathedral) - 2H Mace" },
			[15] = { str = "#ACCEPT- Illusionary Rod# (SM Library Doan) - Caster staff" },
			[16] = { str = "#ACCEPT- Whitemane's Chapeau# (SM Cathedral) - Healer hat" },
			[17] = { str = "#DOQUESTLevel 40-50 Weapons#:" },
			[18] = { str = "#ACCEPT- Sang'thraze + Jang'thraze = Sul'thraze# (ZF) - 2H Sword" },
			[19] = { str = "#ACCEPT- Hammer of the Vesper# (Uldaman) - 1H Mace" },
			[20] = { str = "#ACCEPT- Thrash Blade# (Quest: Maraudon) - Sword with procs" },
			[21] = { str = "#ACCEPT- Princess Theradras's Scepter# (Maraudon) - Caster mace" },
			[22] = { str = "#DOQUESTLevel 50-60 Weapons#:" },
			[23] = { str = "#ACCEPT- Blackhand Doomsaw# (LBRS quest) - 2H Sword" },
			[24] = { str = "#ACCEPT- Mirah's Song# (Scholo quest) - Great sword" },
			[25] = { str = "#ACCEPT- Lord General's Sword# (Scholo) - 1H Sword" },
			[26] = { str = "#ACCEPT- Mass of McGowan# (BRD Plugger) - 1H Mace" },
			[27] = { str = "#DOQUESTKey Armor Sets#:" },
			[28] = { str = "#ACCEPT- Blackened Defias Set# (Deadmines) - Rogue BiS until 30" },
			[29] = { str = "#ACCEPT- Scarlet Set# (SM all wings) - Mail users" },
			[30] = { str = "#ACCEPT- Devilsaur Set# (Crafted 55+) - Pre-raid BiS for melee" },
			[31] = { str = "#ACCEPT- Dungeon Set 1 (T0)# - Good starter sets at 60" },
			[32] = { str = "#DOQUESTQuest Reward Tips#:" },
			[33] = { str = "#TURNIN- Always pick stat upgrades over gold#" },
			[34] = { str = "#TURNIN- Check AH for cheap green upgrades#" },
			[35] = { str = "#TURNIN- Weapons > Armor for damage dealers#" },
			[36] = { str = "#TURNIN- 'of the Bear/Tiger/Eagle/Owl' suffixes are great#" },
		}
	},
}
